# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
      # Specify service dependencies here if necessary
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache # caches both yarn and cypress, no need to cache node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn verify # formatting, static analysis
      - run: yarn test --maxWorkers=2 # tests
      - run: NODE_ENV=production RUNTIME_ENV=dev yarn build # building the app to see if build works and prepare dist for cypress
      #- run: yarn cypress run # ui tests

workflows:
  version: 2
  build_deploy_latest:
    jobs:
      - build:
          filters:
            branches:
              only: master
